app/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{

    use TimestampableEntity;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_family;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="author")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameFamily(): ?string
    {
        return $this->name_family;
    }

    public function setNameFamily(string $name_family): self
    {
        $this->name_family = $name_family;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
        // $this->password =null;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setAuthor($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getAuthor() === $this) {
                $product->setAuthor(null);
            }
        }

        return $this;
    }
}

app/templates/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}
        {# 'app' must match the first argument to addEntry() in webpack.config.js #}
        {{ encore_entry_link_tags('app') }}

        <!-- Renders a link tag (if your module requires any CSS)
             <link rel="stylesheet" href="/build/app.css"> -->
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}"/>
</head>
<body class="rtl">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item{{ app.request.get('_route') == 'app_homepage' ? ' active' }}">
                <a class="nav-link" href="{{ path('app_homepage') }}">{{ "Products" | trans }}</a>
            </li>
            {% if app.user %}
                {% if is_granted('ROLE_ADMIN') %}
                    <li class="nav-item{{ app.request.get('_route') == 'product_index' or app.request.get('_route') == 'product_index' ? ' active' }}">
                        <a class="nav-link" href="{{ path('product_index') }}">{{ "Manage Products" | trans }}</a>
                    </li>
                {% endif %}
                <li class="nav-item {{ app.request.get('_route') == 'profile' ? 'active' }}">
                    <a class="nav-link">{{ app.user.nameFamily }}</a>
                </li>
                <li class="nav-item {{ app.request.get('_route') == 'app_logout' ? 'active' }}">
                    <a class="nav-link" href="{{ logout_path() }}">{{ "Logout"|trans }}</a>
                </li>
            {% else %}
                <li class="nav-item {{ app.request.get('_route') == 'app_login' ? 'active' }}">
                    <a class="nav-link" href="{{ path('app_login') }}">{{ "Sign in"|trans }}</a>
                </li>
                <li class="nav-item {{ app.request.get('_route') == 'app_register' ? 'active' }}">
                    <a class="nav-link" href="{{ path('app_register') }}">{{ "Register"|trans }}</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item{{ app.request.get('_route') == 'advance_search' ? ' active' }}">
                <a class="nav-link" href="{{ path('advance_search') }}">{{ "Advance Search" | trans }}</a>
            </li>
            <li>
                <form class="form-inline my-2 my-lg-0" action="{{ path('app_homepage') }}">
                    <input class="form-control mr-sm-2" name="s" type="search" {% if app.request.query.has("s") %}
                           value="{{ app.request.query.filter("s")|trim }}"
                           {% endif %}placeholder="{{ "Search"|trans }}"
                           aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{{ "Search"|trans }}</button>
                </form>
            </li>
        </ul>
    </div>
</nav>
<div class="container">{% block body %}{% endblock %}</div>
{% block javascripts %}
    {{ encore_entry_script_tags('app') }}

    <!-- Renders app.js & a webpack runtime.js file
        <script src="/build/runtime.js"></script>
        <script src="/build/app.js"></script> -->
{% endblock %}
</body>
</html>

app/templates/jquery.collection.html.twig
{#
# jquery.collection.html.twig
#
# Adds the following html attributes to the root node of your collection fields:
#
# - data-prototype-name: placeholder used in the prototype to replace element indexes on the collection
# - data-allow-add: if set to false, plugin will automatically set allow_add option to false
# - data-allow-delete: if set to false, plugin will automatically set allow_remove option to false
# - data-name-prefix: contains the collection's prefix used in descendant field names
#
# Those information let you configure the plugin options automatically.
#
# If you are already using a form theme, you can use both by using:
# {%
#   form_theme myForm
#       'FuzAppBundle::my-form-theme.html.twig'
#       'FuzAppBundle::jquery.collection.html.twig'
#       ...
# %}
#}

{% block collection_widget %}
    {% apply spaceless %}
        {% if prototype is defined %}
            {% set attr = attr|merge({'data-prototype': form_row(prototype)}) %}
            {% set attr = attr|merge({'data-prototype-name': prototype.vars.name}) %}
        {% endif %}
        {% set attr = attr|merge({'data-allow-add': allow_add ? 1 : 0}) %}
        {% set attr = attr|merge({'data-allow-remove': allow_delete ? 1 : 0 }) %}
        {% set attr = attr|merge({'data-name-prefix': full_name}) %}
        {% form_theme form 'jquery.collection.html.twig' %}
        {{ block('form_widget') }}
    {% endapply %}
{% endblock collection_widget %}